version: "3.8"

name: sch_sw_uni_dev

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-dev
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-container-dev
    shm_size: 2g
    environment:
      - TZ=Asia/Seoul
    ports:
      - "4444:4444"

  java:
    image: eclipse-temurin:17
    container_name: java-app-container-dev
    restart: on-failure
    working_dir: /app
    volumes:
      - ./build/libs:/app
    environment:
      - TZ=Asia/Seoul
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DISCORD_TOKEN=${BOT_TOKEN}
    command: ["java", "-jar", "SchNoticeBot.jar"]
    depends_on:
      - mysql
      - selenium

